RADGENORM_ABNORMALITY_QUESTION_DICT = {
    1: "What are the abnormalities in the {region}?",
    2: "What abnormalities are present in the {region}?",
    3: "What types of abnormality are visible in the {region}?",
    4: "What type of abnormality is visible in the {region}?",
    5: "What kind of abnormalities are observed in the {region}?",
    6: "What kinds of abnormalities can be identified in the {region}?",
    7: "What specific abnormalities are detected in the {region}?",
    8: "What specific types of abnormalities are evident in the {region}?",
    9: "What types of abnormalities are evident upon examination of the {region}?",
    10: "What types of abnormalities can be seen in the {region}?",
    11: "What are the anomalies in the {region}?",
    12: "What anomalies are present in the {region}?",
    13: "What types of anomalies are visible in the {region}?",
    14: "What type of anomalies is visible in the {region}?",
    15: "What kind of anomalies are observed in the {region}?",
    16: "What kinds of anomalies can be identified in the {region}?",
    17: "What specific anomalies are detected in the {region}?",
    18: "What specific types of anomalies are evident in the {region}?",
    19: "What types of anomalies are evident upon examination of the {region}?",
    20: "What types of anomalies can be seen in the {region}?",
    21: "What are the abnormal findings in the {region}?",
    22: "What abnormal findings are present in the {region}?",
    23: "What types of abnormal findings are visible in the {region}?",
    24: "What type of abnormal findings is visible in the {region}?",
    25: "What kind of abnormal findings are observed in the {region}?",
    26: "What kinds of abnormal findings can be identified in the {region}?",
    27: "What specific abnormal findings are detected in the {region}?",
    28: "What specific types of abnormal findings are evident in the {region}?",
    29: "What types of abnormal findings are evident upon examination of the {region}?",
    30: "What types of abnormal findings can be seen in the {region}?",
    31: "What are the irregular findings in the {region}?",
    32: "What irregular findings are present in the {region}?",
    33: "What types of irregular findings are visible in the {region}?",
    34: "What type of irregular findings is visible in the {region}?",
    35: "What kind of irregular findings are observed in the {region}?",
    36: "What kinds of irregular findings can be identified in the {region}?",
    37: "What specific irregular findings are detected in the {region}?",
    38: "What specific types of irregular findings are evident in the {region}?",
    39: "What types of irregular findings are evident upon examination of the {region}?",
    40: "What types of irregular findings can be seen in the {region}?",
    41: "What are the irregularities in the {region}?",
    42: "What irregularities are present in the {region}?",
    43: "What types of irregularities are visible in the {region}?",
    44: "What type of irregularities is visible in the {region}?",
    45: "What kind of irregularities are observed in the {region}?",
    46: "What kinds of irregularities can be identified in the {region}?",
    47: "What specific irregularities are detected in the {region}?",
    48: "What specific types of irregularities are evident in the {region}?",
    49: "What types of irregularities are evident upon examination of the {region}?",
    50: "What types of irregularities can be seen in the {region}?"
}

RADGENORM_PRESENCE_QUESTION_DICT = {
    1: "Can {abnormality} be identified in the {region}?",
    2: "Can {abnormality} be observed in the {region}?",
    3: "Can {abnormality} be detected in the {region}?",
    4: "Can {abnormality} be seen in the {region}?",
    5: "Can {abnormality} be found in the {region}?",
    6: "Can {abnormality} be recognized in the {region}?",
    7: "Can we detect any signs of {abnormality} in the {region}?",
    8: "Can we observe any signs of {abnormality} in the {region}?",
    9: "Can we recognize any signs of {abnormality} in the {region}?",
    10: "Can we see {abnormality} in the {region}?",
    11: "Can we find {abnormality} in the {region}?",
    12: "Can we detect {abnormality} in the {region}?",
    13: "Can we observe {abnormality} in the {region}?",
    14: "Can we identify {abnormality} in the {region}?",
    15: "Is there any sign of {abnormality} in the {region}?",
    16: "Is there any indication of {abnormality} in the {region}?",
    17: "Is there any evidence of {abnormality} in the {region}?",
    18: "Is there any suggestion of {abnormality} in the {region}?",
    19: "Is there a clear sign of {abnormality} in the {region}?",
    20: "Is there a clear indication of {abnormality} in the {region}?",
    21: "Is there clear evidence of {abnormality} in the {region}?",
    22: "Is there a clear suggestion of {abnormality} in the {region}?",
    23: "Is {abnormality} visibly present in the {region}?",
    24: "Is {abnormality} clearly visible in the {region}?",
    25: "Is there any visual evidence suggesting {abnormality} in the {region}?",
    26: "Is there any indication of {abnormality} upon examination of the {region}?",
    27: "Is there any indication of {abnormality} in the {region}?",
    28: "Is there visual evidence of {abnormality} in the {region} on this scan?",
    29: "Are there any visible indications of {abnormality} in this {region}?",
    30: "Are there any visible cues indicating {abnormality} in the {region}?",
    31: "Are there any visible indicators of {abnormality} in the {region}?",
    32: "Are there any clear indications of {abnormality} in this {region}?",
    33: "Are there any clear cues indicating {abnormality} in the {region}?",
    34: "Are there any clear indicators of {abnormality} in the {region}?",
    35: "Are there any indications of {abnormality} in this {region}?",
    36: "Are there any cues indicating {abnormality} in the {region}?",
    37: "Are there any indicators of {abnormality} in the {region}?",
    38: "Are there any observable signs of {abnormality} in the {region}?",
    39: "Are there any signs of {abnormality} in the {region}?",
    40: "Are there any features of {abnormality} in the {region}?",
    41: "Does the {region} show the presence of {abnormality}?",
    42: "Does the {region} show the existence of {abnormality}?",
    43: "Does the image suggest the presence of {abnormality} in the {region}?",
    44: "Does the image suggest the existence of {abnormality} in the {region}?",
    45: "Does the {region} exhibit any evidence of {abnormality}?",
    46: "Does the {region} display any features suggestive of {abnormality}?",
    47: "Does the {region} display any characteristics suggestive of {abnormality}?",
    48: "Does the {region} exhibit any characteristics indicative of {abnormality}?",
    49: "Does the {region} exhibit any features indicative of {abnormality}?",
    50: "Does the visual features suggest the presence of {abnormality} in the {region}?"
}

RADGENORM_LOCATION_QUESTION_DICT = {
    1: "Where is the {abnormality} located in the image?",
    2: "Where can the {abnormality} be found within the image?",
    3: "Where in the image is the {abnormality} located?",
    4: "Where in the image is the {abnormality} localized?",
    5: "Where in the image can the {abnormality} be found?",
    6: "Where in the image does the {abnormality} appear?",
    7: "Where in the image does the {abnormality} locate?",
    8: "Where in the image does the {abnormality} locate?",
    9: "Where specifically within the image is the {abnormality} located?",
    10: "Where exactly within the image is the {abnormality} located?",
    11: "Where exactly is the {abnormality} located in the image?",
    12: "Where specifically is the {abnormality} located in the image?",
    13: "Where exactly within the image is the {abnormality} localized?",
    14: "Where specifically within the image is the {abnormality} localized?",
    15: "Where within the image can the {abnormality} be precisely located?",
    16: "Where exactly within the image does the {abnormality} present?",
    17: "Where within the image does the {abnormality} specifically present?",
    18: "Where in the image does the {abnormality} appear?",
    19: "What is the location of the {abnormality} in the image?",
    20: "What is the precise location of the {abnormality} in the image?",
    21: "What is the specific location of the {abnormality} within the image?",
    22: "What is the precise region of the {abnormality} in the image?",
    23: "What is the specific region of the {abnormality} within the image?",
    24: "What particular region within the image does the {abnormality} occupy?",
    25: "What particular location within the image does the {abnormality} occupy?",
    26: "What specific location within the image does the {abnormality} occupy?",
    27: "What specific region within the image does the {abnormality} occupy?",
    28: "What specific area of the image does the {abnormality} occupy?",
    29: "What specific region of the image does the {abnormality} appear?",
    30: "What specific spot within the image contains the {abnormality}?",
    31: "What particular region of the image is affected by the {abnormality}?",
    32: "What specific area within the image is impacted by the {abnormality}?",
    33: "What specific region within the image is impacted by the {abnormality}?",
    34: "What specific location within the image is impacted by the {abnormality}?",
    35: "What particular region within the image is affected by the {abnormality}?",
    36: "What particular area within the image is affected by the {abnormality}?",
    37: "What particular location within the image is affected by the {abnormality}?",
    38: "What specific region within the image does the {abnormality} affect?",
    39: "What specific area within the image does the {abnormality} affect?",
    40: "What specific location within the image does the {abnormality} affect?",
    41: "What specific location within the image does the {abnormality} appear?",
    42: "What specific region within the image does the {abnormality} appear?",
    43: "What specific area within the image does the {abnormality} appear?",
    44: "What particular spot within the image does the {abnormality} present?",
    45: "What particular area within the image does the {abnormality} present?",
    46: "What particular region within the image does the {abnormality} present?",
    47: "What particular location within the image does the {abnormality} present?",
    48: "What specific area within the image does the {abnormality} occur?",
    49: "What specific location within the image does the {abnormality} occur?",
    50: "What specific region within the image does the {abnormality} occur?"
}
